// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/spotify.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/spotify/login.tsx";
import * as $4 from "./routes/spotify/success.tsx";
import * as $$0 from "./islands/Home.tsx";
import * as $$1 from "./islands/Spotify.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/spotify.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/spotify/login.tsx": $3,
    "./routes/spotify/success.tsx": $4,
  },
  islands: {
    "./islands/Home.tsx": $$0,
    "./islands/Spotify.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
